# Generated by Django 3.0.3 on 2020-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('real_name', models.CharField(max_length=20)),
                ('tz', models.CharField(max_length=30)),
            ],
        ),
    ]
