# Generated by Django 3.0.3 on 2020-06-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='activity_period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Activity'),
        ),
    ]
