# Generated by Django 3.0.3 on 2020-06-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200625_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_period',
            name='stime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_period', to='demo.User'),
        ),
    ]
