# Generated by Django 3.0.3 on 2020-06-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200625_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_period',
            name='stime',
        ),
        migrations.AddField(
            model_name='activity_period',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity_period',
            name='time',
            field=models.ManyToManyField(related_name='activity_period', to='demo.User'),
        ),
        migrations.AlterField(
            model_name='activity_period',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
